/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 44
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_domain_keyword = 2,
  sym_dns_file_name_keyword = 3,
  sym_reverse_dns_file_name_keyword = 4,
  sym_dhcp_file_name_keyword = 5,
  sym_mac_address = 6,
  sym_ip_address = 7,
  sym_hostname = 8,
  sym_comment = 9,
  sym_filename = 10,
  sym_dns_prefix_keyword = 11,
  sym_dns_suffix_keyword = 12,
  sym_dhcp_prefix_keyword = 13,
  sym_string_content = 14,
  sym_string_delimiter = 15,
  sym_source_file = 16,
  sym_ip_config_line = 17,
  sym__extra_config_line = 18,
  sym_domain = 19,
  sym_dns_file_name = 20,
  sym_reverse_dns_file_name = 21,
  sym_dhcp_file_name = 22,
  sym__rule = 23,
  sym_dns_prefix_section = 24,
  sym_dns_suffix_section = 25,
  sym_dhcp_prefix_section = 26,
  sym_string = 27,
  aux_sym_source_file_repeat1 = 28,
  aux_sym__rule_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_domain_keyword] = "domain_keyword",
  [sym_dns_file_name_keyword] = "dns_file_name_keyword",
  [sym_reverse_dns_file_name_keyword] = "reverse_dns_file_name_keyword",
  [sym_dhcp_file_name_keyword] = "dhcp_file_name_keyword",
  [sym_mac_address] = "mac_address",
  [sym_ip_address] = "ip_address",
  [sym_hostname] = "hostname",
  [sym_comment] = "comment",
  [sym_filename] = "filename",
  [sym_dns_prefix_keyword] = "dns_prefix_keyword",
  [sym_dns_suffix_keyword] = "dns_suffix_keyword",
  [sym_dhcp_prefix_keyword] = "dhcp_prefix_keyword",
  [sym_string_content] = "string_content",
  [sym_string_delimiter] = "string_delimiter",
  [sym_source_file] = "source_file",
  [sym_ip_config_line] = "ip_config_line",
  [sym__extra_config_line] = "_extra_config_line",
  [sym_domain] = "domain",
  [sym_dns_file_name] = "dns_file_name",
  [sym_reverse_dns_file_name] = "reverse_dns_file_name",
  [sym_dhcp_file_name] = "dhcp_file_name",
  [sym__rule] = "_rule",
  [sym_dns_prefix_section] = "dns_prefix_section",
  [sym_dns_suffix_section] = "dns_suffix_section",
  [sym_dhcp_prefix_section] = "dhcp_prefix_section",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__rule_repeat1] = "_rule_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_domain_keyword] = sym_domain_keyword,
  [sym_dns_file_name_keyword] = sym_dns_file_name_keyword,
  [sym_reverse_dns_file_name_keyword] = sym_reverse_dns_file_name_keyword,
  [sym_dhcp_file_name_keyword] = sym_dhcp_file_name_keyword,
  [sym_mac_address] = sym_mac_address,
  [sym_ip_address] = sym_ip_address,
  [sym_hostname] = sym_hostname,
  [sym_comment] = sym_comment,
  [sym_filename] = sym_filename,
  [sym_dns_prefix_keyword] = sym_dns_prefix_keyword,
  [sym_dns_suffix_keyword] = sym_dns_suffix_keyword,
  [sym_dhcp_prefix_keyword] = sym_dhcp_prefix_keyword,
  [sym_string_content] = sym_string_content,
  [sym_string_delimiter] = sym_string_delimiter,
  [sym_source_file] = sym_source_file,
  [sym_ip_config_line] = sym_ip_config_line,
  [sym__extra_config_line] = sym__extra_config_line,
  [sym_domain] = sym_domain,
  [sym_dns_file_name] = sym_dns_file_name,
  [sym_reverse_dns_file_name] = sym_reverse_dns_file_name,
  [sym_dhcp_file_name] = sym_dhcp_file_name,
  [sym__rule] = sym__rule,
  [sym_dns_prefix_section] = sym_dns_prefix_section,
  [sym_dns_suffix_section] = sym_dns_suffix_section,
  [sym_dhcp_prefix_section] = sym_dhcp_prefix_section,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__rule_repeat1] = aux_sym__rule_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_domain_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_dns_file_name_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_reverse_dns_file_name_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_dhcp_file_name_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_mac_address] = {
    .visible = true,
    .named = true,
  },
  [sym_ip_address] = {
    .visible = true,
    .named = true,
  },
  [sym_hostname] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_filename] = {
    .visible = true,
    .named = true,
  },
  [sym_dns_prefix_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_dns_suffix_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_dhcp_prefix_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_string_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_ip_config_line] = {
    .visible = true,
    .named = true,
  },
  [sym__extra_config_line] = {
    .visible = false,
    .named = true,
  },
  [sym_domain] = {
    .visible = true,
    .named = true,
  },
  [sym_dns_file_name] = {
    .visible = true,
    .named = true,
  },
  [sym_reverse_dns_file_name] = {
    .visible = true,
    .named = true,
  },
  [sym_dhcp_file_name] = {
    .visible = true,
    .named = true,
  },
  [sym__rule] = {
    .visible = false,
    .named = true,
  },
  [sym_dns_prefix_section] = {
    .visible = true,
    .named = true,
  },
  [sym_dns_suffix_section] = {
    .visible = true,
    .named = true,
  },
  [sym_dhcp_prefix_section] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__rule_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 23,
  [42] = 32,
  [43] = 31,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(106);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == ';') ADVANCE(120);
      if (lookahead == 'D') ADVANCE(22);
      if (lookahead == 'd') ADVANCE(63);
      if (lookahead == 'r') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(107);
      if (lookahead == ';') ADVANCE(120);
      if (lookahead == '@') ADVANCE(116);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(127);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(91);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(91);
      if (lookahead == '-' ||
          lookahead == ':') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(86);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(92);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(93);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == '.') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == ';') ADVANCE(120);
      if (lookahead == '@') ADVANCE(116);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 14:
      if (lookahead == ';') ADVANCE(120);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 15:
      if (lookahead == 'C') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'F') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'F') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'F') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'F') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'H') ADVANCE(15);
      if (lookahead == 'N') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(86);
      END_STATE();
    case 23:
      if (lookahead == 'I') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'I') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'I') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == 'P') ADVANCE(29);
      if (lookahead == 'S') ADVANCE(32);
      END_STATE();
    case 27:
      if (lookahead == 'P') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == 'P') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 'R') ADVANCE(16);
      END_STATE();
    case 30:
      if (lookahead == 'R') ADVANCE(17);
      END_STATE();
    case 31:
      if (lookahead == 'S') ADVANCE(36);
      END_STATE();
    case 32:
      if (lookahead == 'U') ADVANCE(20);
      END_STATE();
    case 33:
      if (lookahead == 'X') ADVANCE(122);
      END_STATE();
    case 34:
      if (lookahead == 'X') ADVANCE(123);
      END_STATE();
    case 35:
      if (lookahead == 'X') ADVANCE(124);
      END_STATE();
    case 36:
      if (lookahead == '_') ADVANCE(26);
      END_STATE();
    case 37:
      if (lookahead == '_') ADVANCE(60);
      END_STATE();
    case 38:
      if (lookahead == '_') ADVANCE(50);
      END_STATE();
    case 39:
      if (lookahead == '_') ADVANCE(28);
      END_STATE();
    case 40:
      if (lookahead == '_') ADVANCE(76);
      END_STATE();
    case 41:
      if (lookahead == '_') ADVANCE(77);
      END_STATE();
    case 42:
      if (lookahead == '_') ADVANCE(78);
      END_STATE();
    case 43:
      if (lookahead == '_') ADVANCE(61);
      END_STATE();
    case 44:
      if (lookahead == '_') ADVANCE(62);
      END_STATE();
    case 45:
      if (lookahead == 'a') ADVANCE(64);
      END_STATE();
    case 46:
      if (lookahead == 'a') ADVANCE(72);
      END_STATE();
    case 47:
      if (lookahead == 'a') ADVANCE(73);
      END_STATE();
    case 48:
      if (lookahead == 'a') ADVANCE(74);
      END_STATE();
    case 49:
      if (lookahead == 'c') ADVANCE(80);
      END_STATE();
    case 50:
      if (lookahead == 'd') ADVANCE(79);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(109);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(111);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(110);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 60:
      if (lookahead == 'f') ADVANCE(65);
      END_STATE();
    case 61:
      if (lookahead == 'f') ADVANCE(66);
      END_STATE();
    case 62:
      if (lookahead == 'f') ADVANCE(67);
      END_STATE();
    case 63:
      if (lookahead == 'h') ADVANCE(49);
      if (lookahead == 'n') ADVANCE(82);
      if (lookahead == 'o') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(86);
      END_STATE();
    case 64:
      if (lookahead == 'i') ADVANCE(75);
      END_STATE();
    case 65:
      if (lookahead == 'i') ADVANCE(68);
      END_STATE();
    case 66:
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 67:
      if (lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 68:
      if (lookahead == 'l') ADVANCE(57);
      END_STATE();
    case 69:
      if (lookahead == 'l') ADVANCE(58);
      END_STATE();
    case 70:
      if (lookahead == 'l') ADVANCE(59);
      END_STATE();
    case 71:
      if (lookahead == 'm') ADVANCE(45);
      END_STATE();
    case 72:
      if (lookahead == 'm') ADVANCE(53);
      END_STATE();
    case 73:
      if (lookahead == 'm') ADVANCE(54);
      END_STATE();
    case 74:
      if (lookahead == 'm') ADVANCE(55);
      END_STATE();
    case 75:
      if (lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 76:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 77:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 79:
      if (lookahead == 'n') ADVANCE(84);
      END_STATE();
    case 80:
      if (lookahead == 'p') ADVANCE(43);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(83);
      END_STATE();
    case 82:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 83:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 84:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 85:
      if (lookahead == 'v') ADVANCE(52);
      END_STATE();
    case 86:
      if (lookahead == '-' ||
          lookahead == ':') ADVANCE(104);
      END_STATE();
    case 87:
      if (lookahead == '-' ||
          lookahead == ':') ADVANCE(96);
      END_STATE();
    case 88:
      if (lookahead == '-' ||
          lookahead == ':') ADVANCE(98);
      END_STATE();
    case 89:
      if (lookahead == '-' ||
          lookahead == ':') ADVANCE(100);
      END_STATE();
    case 90:
      if (lookahead == '-' ||
          lookahead == ':') ADVANCE(102);
      END_STATE();
    case 91:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 92:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 93:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 94:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(86);
      END_STATE();
    case 95:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(112);
      END_STATE();
    case 96:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(95);
      END_STATE();
    case 97:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      END_STATE();
    case 98:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(97);
      END_STATE();
    case 99:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(88);
      END_STATE();
    case 100:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(99);
      END_STATE();
    case 101:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(89);
      END_STATE();
    case 102:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(101);
      END_STATE();
    case 103:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(90);
      END_STATE();
    case 104:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(103);
      END_STATE();
    case 105:
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(126);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_domain_keyword);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_dns_file_name_keyword);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_reverse_dns_file_name_keyword);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_dhcp_file_name_keyword);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_mac_address);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_ip_address);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_ip_address);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_ip_address);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_hostname);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_hostname);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(126);
      if (lookahead == '"') ADVANCE(120);
      if (lookahead != 0) ADVANCE(119);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(126);
      if (lookahead == '"') ADVANCE(118);
      if (lookahead != 0) ADVANCE(119);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_filename);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_dns_prefix_keyword);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_dns_suffix_keyword);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_dhcp_prefix_keyword);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '"') ADVANCE(105);
      if (lookahead == ';') ADVANCE(119);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(125);
      if (lookahead != 0) ADVANCE(126);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '"') ADVANCE(105);
      if (lookahead != 0) ADVANCE(126);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_string_delimiter);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 14},
  [31] = {.lex_state = 125},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 14},
  [37] = {.lex_state = 14},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 125},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_domain_keyword] = ACTIONS(1),
    [sym_dns_file_name_keyword] = ACTIONS(1),
    [sym_reverse_dns_file_name_keyword] = ACTIONS(1),
    [sym_dhcp_file_name_keyword] = ACTIONS(1),
    [sym_mac_address] = ACTIONS(1),
    [sym_ip_address] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_dns_prefix_keyword] = ACTIONS(1),
    [sym_dns_suffix_keyword] = ACTIONS(1),
    [sym_dhcp_prefix_keyword] = ACTIONS(1),
    [sym_string_delimiter] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(35),
    [sym_ip_config_line] = STATE(2),
    [sym__extra_config_line] = STATE(2),
    [sym_domain] = STATE(2),
    [sym_dns_file_name] = STATE(2),
    [sym_reverse_dns_file_name] = STATE(2),
    [sym_dhcp_file_name] = STATE(2),
    [sym__rule] = STATE(4),
    [sym_dns_prefix_section] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_domain_keyword] = ACTIONS(5),
    [sym_dns_file_name_keyword] = ACTIONS(7),
    [sym_reverse_dns_file_name_keyword] = ACTIONS(9),
    [sym_dhcp_file_name_keyword] = ACTIONS(11),
    [sym_mac_address] = ACTIONS(13),
    [sym_ip_address] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [sym_dns_prefix_keyword] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym_ip_config_line] = STATE(3),
    [sym__extra_config_line] = STATE(3),
    [sym_domain] = STATE(3),
    [sym_dns_file_name] = STATE(3),
    [sym_reverse_dns_file_name] = STATE(3),
    [sym_dhcp_file_name] = STATE(3),
    [sym__rule] = STATE(4),
    [sym_dns_prefix_section] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_domain_keyword] = ACTIONS(5),
    [sym_dns_file_name_keyword] = ACTIONS(7),
    [sym_reverse_dns_file_name_keyword] = ACTIONS(9),
    [sym_dhcp_file_name_keyword] = ACTIONS(11),
    [sym_mac_address] = ACTIONS(13),
    [sym_ip_address] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [sym_dns_prefix_keyword] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym_ip_config_line] = STATE(3),
    [sym__extra_config_line] = STATE(3),
    [sym_domain] = STATE(3),
    [sym_dns_file_name] = STATE(3),
    [sym_reverse_dns_file_name] = STATE(3),
    [sym_dhcp_file_name] = STATE(3),
    [sym__rule] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_domain_keyword] = ACTIONS(19),
    [sym_dns_file_name_keyword] = ACTIONS(22),
    [sym_reverse_dns_file_name_keyword] = ACTIONS(25),
    [sym_dhcp_file_name_keyword] = ACTIONS(28),
    [sym_mac_address] = ACTIONS(31),
    [sym_ip_address] = ACTIONS(34),
    [sym_comment] = ACTIONS(3),
    [sym_dns_prefix_keyword] = ACTIONS(37),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 7,
      sym_domain_keyword,
      sym_dns_file_name_keyword,
      sym_reverse_dns_file_name_keyword,
      sym_dhcp_file_name_keyword,
      sym_mac_address,
      sym_ip_address,
      sym_dns_prefix_keyword,
  [13] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 7,
      sym_domain_keyword,
      sym_dns_file_name_keyword,
      sym_reverse_dns_file_name_keyword,
      sym_dhcp_file_name_keyword,
      sym_mac_address,
      sym_ip_address,
      sym_dns_prefix_keyword,
  [26] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 7,
      sym_domain_keyword,
      sym_dns_file_name_keyword,
      sym_reverse_dns_file_name_keyword,
      sym_dhcp_file_name_keyword,
      sym_mac_address,
      sym_ip_address,
      sym_dns_prefix_keyword,
  [39] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 7,
      sym_domain_keyword,
      sym_dns_file_name_keyword,
      sym_reverse_dns_file_name_keyword,
      sym_dhcp_file_name_keyword,
      sym_mac_address,
      sym_ip_address,
      sym_dns_prefix_keyword,
  [52] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 7,
      sym_domain_keyword,
      sym_dns_file_name_keyword,
      sym_reverse_dns_file_name_keyword,
      sym_dhcp_file_name_keyword,
      sym_mac_address,
      sym_ip_address,
      sym_dns_prefix_keyword,
  [65] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 7,
      sym_domain_keyword,
      sym_dns_file_name_keyword,
      sym_reverse_dns_file_name_keyword,
      sym_dhcp_file_name_keyword,
      sym_mac_address,
      sym_ip_address,
      sym_dns_prefix_keyword,
  [78] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 7,
      sym_domain_keyword,
      sym_dns_file_name_keyword,
      sym_reverse_dns_file_name_keyword,
      sym_dhcp_file_name_keyword,
      sym_mac_address,
      sym_ip_address,
      sym_dns_prefix_keyword,
  [91] = 4,
    ACTIONS(53), 1,
      anon_sym_LF,
    ACTIONS(55), 1,
      sym_hostname,
    ACTIONS(57), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym__rule_repeat1,
  [104] = 4,
    ACTIONS(57), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LF,
    ACTIONS(61), 1,
      sym_hostname,
    STATE(12), 1,
      aux_sym__rule_repeat1,
  [117] = 4,
    ACTIONS(55), 1,
      sym_hostname,
    ACTIONS(57), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LF,
    STATE(12), 1,
      aux_sym__rule_repeat1,
  [130] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_dns_suffix_keyword,
    STATE(19), 1,
      sym_dns_suffix_section,
  [140] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_string_delimiter,
    STATE(34), 1,
      sym_string,
  [150] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      sym_hostname,
    STATE(13), 1,
      aux_sym__rule_repeat1,
  [160] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_hostname,
    STATE(11), 1,
      aux_sym__rule_repeat1,
  [170] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_string_delimiter,
    STATE(33), 1,
      sym_string,
  [180] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_dhcp_prefix_keyword,
    STATE(24), 1,
      sym_dhcp_prefix_section,
  [190] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_dns_suffix_keyword,
    STATE(22), 1,
      sym_dns_suffix_section,
  [200] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      sym_string_delimiter,
    STATE(39), 1,
      sym_string,
  [210] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_dhcp_prefix_keyword,
    STATE(40), 1,
      sym_dhcp_prefix_section,
  [220] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 2,
      sym_dns_suffix_keyword,
      sym_dhcp_prefix_keyword,
  [228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
  [235] = 2,
    ACTIONS(57), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LF,
  [242] = 2,
    ACTIONS(57), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_LF,
  [249] = 2,
    ACTIONS(57), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_LF,
  [256] = 2,
    ACTIONS(57), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LF,
  [263] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_hostname,
  [270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_filename,
  [277] = 2,
    ACTIONS(57), 1,
      sym_comment,
    ACTIONS(94), 1,
      sym_string_content,
  [284] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym_string_delimiter,
  [291] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym_dhcp_prefix_keyword,
  [298] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      sym_dns_suffix_keyword,
  [305] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
  [312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_filename,
  [319] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      sym_filename,
  [326] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      sym_ip_address,
  [333] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
  [340] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
  [347] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
  [354] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_string_delimiter,
  [361] = 2,
    ACTIONS(57), 1,
      sym_comment,
    ACTIONS(116), 1,
      sym_string_content,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 13,
  [SMALL_STATE(6)] = 26,
  [SMALL_STATE(7)] = 39,
  [SMALL_STATE(8)] = 52,
  [SMALL_STATE(9)] = 65,
  [SMALL_STATE(10)] = 78,
  [SMALL_STATE(11)] = 91,
  [SMALL_STATE(12)] = 104,
  [SMALL_STATE(13)] = 117,
  [SMALL_STATE(14)] = 130,
  [SMALL_STATE(15)] = 140,
  [SMALL_STATE(16)] = 150,
  [SMALL_STATE(17)] = 160,
  [SMALL_STATE(18)] = 170,
  [SMALL_STATE(19)] = 180,
  [SMALL_STATE(20)] = 190,
  [SMALL_STATE(21)] = 200,
  [SMALL_STATE(22)] = 210,
  [SMALL_STATE(23)] = 220,
  [SMALL_STATE(24)] = 228,
  [SMALL_STATE(25)] = 235,
  [SMALL_STATE(26)] = 242,
  [SMALL_STATE(27)] = 249,
  [SMALL_STATE(28)] = 256,
  [SMALL_STATE(29)] = 263,
  [SMALL_STATE(30)] = 270,
  [SMALL_STATE(31)] = 277,
  [SMALL_STATE(32)] = 284,
  [SMALL_STATE(33)] = 291,
  [SMALL_STATE(34)] = 298,
  [SMALL_STATE(35)] = 305,
  [SMALL_STATE(36)] = 312,
  [SMALL_STATE(37)] = 319,
  [SMALL_STATE(38)] = 326,
  [SMALL_STATE(39)] = 333,
  [SMALL_STATE(40)] = 340,
  [SMALL_STATE(41)] = 347,
  [SMALL_STATE(42)] = 354,
  [SMALL_STATE(43)] = 361,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ip_config_line, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dns_file_name, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dhcp_file_name, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reverse_dns_file_name, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__rule, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__rule_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__rule_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dns_suffix_section, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dns_prefix_section, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dhcp_prefix_section, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_orgncf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "orgncf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
